spark.master                                            yarn
spark.submit.deployMode                                 client
spark.ui.enabled                                        true
spark.ui.port                                           9091
spark.hadoop.fs.defaultFS                               hdfs://masternode:9000
spark.hadoop.yarn.resourcemanager.hostname              masternode

spark.eventLog.enabled                                  true
spark.eventLog.dir                                      hdfs://masternode:9000/spark_events
spark.history.fs.logDirectory                           hdfs://masternode:9000/spark_events

spark.sql.warehouse.dir                                 hdfs://masternode:9000/lakehouse

spark.jars.packages                                     org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.9.2
spark.sql.extensions                                    org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.spark_catalog                         org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.spark_catalog.type                    hadoop
spark.sql.catalog.spark_catalog.warehouse               hdfs://masternode:9000/lakehouse

spark.sql.catalog.hadoop_prod                           org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.hadoop_prod.type                      hadoop
spark.sql.catalog.hadoop_prod.warehouse                 hdfs://masternode:9000/lakehouse