FROM eclipse-temurin:11-jdk-jammy

ARG USER_HDFS="root"
ARG BASE_DIR_PATH="/opt"
ARG HADOOP_VERSION="3.4.1"
ARG SPARK_VERSION="3.5.6"
ARG SPARK_ICEBRG_VERSION="3.5"
ARG SCALA_VERSION="2.12"
ARG ICEBERG_VERSION="1.9.2"

ARG PATH_HOST_CONFIG_SERVICES_FILES="/hadoop_platform/configs/services"
ARG PATH_HOST_CONFIG_NODES_FILES="/hadoop_platform/configs/nodes"
ARG PATH_HOST_TEST_FILES="/tests"

# ARG LINK_DOWNLOAD_HADOOP="https://dlcdn.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz"
# ARG LINK_DOWNLOAD_SPARK="https://dlcdn.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz"
# ARG LINK_DOWNLOAD_ICBERG_JAR="https://search.maven.org/remotecontent?filepath=org/apache/iceberg/iceberg-spark-runtime-${SPARK_ICEBRG_VERSION}_${SCALA_VERSION}/${ICEBERG_VERSION}/iceberg-spark-runtime-${SPARK_ICEBRG_VERSION}_${SCALA_VERSION}-${ICEBERG_VERSION}.jar"

ARG LINK_DOWNLOAD_HADOOP="https://downloads.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz"
ARG LINK_DOWNLOAD_SPARK="https://dlcdn.apache.org/spark/spark-3.5.6/spark-3.5.6-bin-hadoop3.tgz"
ARG LINK_DOWNLOAD_ICBERG_JAR="https://search.maven.org/remotecontent?filepath=org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.9.2/iceberg-spark-runtime-3.5_2.12-1.9.2.jar"

ENV PATH_NODE_FILES="/opt/nodes_files"

ENV CONFIGS="${BASE_DIR_PATH}/configs"
ENV NODES_FILES="${BASE_DIR_PATH}/nodes_files"
ENV TESTS="${BASE_DIR_PATH}/tests"
ENV HADOOP_HOME="${BASE_DIR_PATH}/hadoop"
ENV SPARK_HOME="${BASE_DIR_PATH}/spark"

ENV HADOOP_CONF_DIR="${BASE_DIR_PATH}/hadoop/etc/hadoop"
ENV HADOOP_BIN_DIR="${HADOOP_HOME}/bin"
ENV YARN_CONF_DIR="${HADOOP_CONF_DIR}"
ENV LOG_SCRIPT_DIR="/tmp/logs"

ENV SPARK_CONF_DIR="${SPARK_HOME}/conf"
ENV SPARK_SBIN_DIR="${SPARK_HOME}/sbin"
ENV SPARK_BIN_DIR="${SPARK_HOME}/bin"
ENV SPARK_PYTHON_EXAMPLES="${SPARK_HOME}/examples/src/main/python"
ENV SPARK_EVENTS_DIR="${SPARK_HOME}/spark-events"

ENV HDFS_VERSION="${HADOOP_HOME}/dfs/name/current/VERSION"
ENV HDFS_NAMENODE_USER="${USER_HDFS}"
ENV HDFS_DATANODE_USER="${USER_HDFS}"
ENV HDFS_SECONDARYNAMENODE_USER="${USER_HDFS}"

ENV HADOOP_TAR_GZ_FILE="${HADOOP_HOME}/hadoop-${HADOOP_VERSION}.tar.gz"
ENV SPARK_TAR_GZ_FILE="${SPARK_HOME}/spark-${SPARK_VERSION}-bin-hadoop3.tgz"

ENV PATH=$PATH:"$HADOOP_HOME/bin:$HADOOP_HOME/sbin"

ENV ICEBERG_JAR_NAME="iceberg-spark-runtime-3.5_2.12-1.9.2.jar"


RUN apt update && \ 
    apt install -y --no-install-recommends \  
    wget \    
    openssh-client \
    openssh-server \
    python3 \
    rsync \
    wget \
    ssh \
    tini \
    krb5-user \
    libnss3  \
    net-tools \
    inotify-tools    

RUN mkdir -p ${HADOOP_HOME} && \
    mkdir -p ${SPARK_HOME} && \
    wget ${LINK_DOWNLOAD_HADOOP} -O ${HADOOP_TAR_GZ_FILE} && \
    wget ${LINK_DOWNLOAD_SPARK} -O ${SPARK_TAR_GZ_FILE} && \
    wget ${LINK_DOWNLOAD_ICBERG_JAR} -O /opt/spark/jars && \
    tar -xvzf ${HADOOP_TAR_GZ_FILE} -C ${HADOOP_HOME} --strip-components=1 &&\
    tar -xvzf ${SPARK_TAR_GZ_FILE} -C ${SPARK_HOME} --strip-components=1 && \
    rm ${HADOOP_TAR_GZ_FILE} && \
    rm ${SPARK_TAR_GZ_FILE}

RUN mkdir -p ${CONFIGS} && \
    mkdir -p ${TESTS} && \
    mkdir -p ${NODES_FILES} && \
    mkdir -p ${HADOOP_HOME}/dfs/data && \
    mkdir -p ${HADOOP_HOME}/dfs/name && \  
    mkdir -p ${LOG_SCRIPT_DIR} && \
    mkdir -p /tmp/dir && \
    mkdir -p /tmp/spark && \
    mkdir -p ${HADOOP_HOME}/logs


RUN echo "export JAVA_HOME=${JAVA_HOME}" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh

RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys && \
    service ssh start

COPY ${PATH_HOST_CONFIG_SERVICES_FILES}/* ${CONFIGS}
COPY ${PATH_HOST_CONFIG_NODES_FILES}/* ${NODES_FILES}
COPY ${PATH_HOST_TEST_FILES}/* ${TESTS}

RUN mv ${CONFIGS}/logs_yarn.sh ${HADOOP_BIN_DIR}/ && \
    cp ${CONFIGS}/* ${HADOOP_CONF_DIR}/ && \
    cp ${CONFIGS}/* ${SPARK_CONF_DIR}/ && \
    cp ${TESTS}/* ${SPARK_CONF_DIR}/ && \
    rm -r ${CONFIGS} && \
    rm -r ${TESTS}